import { useEffect, useMemo, useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import { ArrowLeft, Award, BarChart3, Check, Clock3, Eye, Globe2, Lightbulb, Play, Shuffle, Volume2 } from "lucide-react";
import { saveGameSession, saveRecommendation } from "../services/api";
import { getLanguageOption, getStoredLanguage, saveLanguage, SUPPORTED_LANGUAGES } from "../i18n/languages";
import type { AppLanguage } from "../i18n/languages";
import "./WhatsMissingGame.css";
import appleImg from "../assets/game-images/food/apple.jpg";
import bananaImg from "../assets/game-images/food/banana.jpg";
import mangoImg from "../assets/game-images/food/mango.jpg";
import strawberryImg from "../assets/game-images/food/strawberry.jpg";
import chairImg from "../assets/game-images/household/chair.jpg";
import clockImg from "../assets/game-images/household/clock.jpg";
import keyImg from "../assets/game-images/household/key.jpg";
import umbrellaImg from "../assets/game-images/household/umbrella.jpg";
import flowerImg from "../assets/game-images/nature/flower.jpg";
import parkImg from "../assets/game-images/nature/park.jpg";
import plantImg from "../assets/game-images/nature/plant.jpg";
import treeImg from "../assets/game-images/nature/tree.jpg";
import dressImg from "../assets/game-images/clothing/dress.jpg";
import glassesImg from "../assets/game-images/clothing/glasses.jpg";
import hatImg from "../assets/game-images/clothing/hat.jpg";
import shoesImg from "../assets/game-images/clothing/shoes.jpg";
import bookImg from "../assets/game-images/everyday/book.jpg";
import bottleImg from "../assets/game-images/everyday/bottle.jpg";
import penImg from "../assets/game-images/everyday/pen.jpg";
import walletImg from "../assets/game-images/everyday/wallet.jpg";

type Difficulty="Easy"|"Medium"|"Hard";
type GamePhase="ready"|"memorize"|"question"|"feedback"|"complete";
type GameItem={id:string;name:string;image:string};
type DifficultyConfig={objects:number;viewTime:number;rounds:number;choices:number};
const GAME_ITEMS:GameItem[]=[
{id:"apple",name:"Apple",image:appleImg},{id:"banana",name:"Banana",image:bananaImg},{id:"mango",name:"Mango",image:mangoImg},{id:"strawberry",name:"Strawberry",image:strawberryImg},
{id:"chair",name:"Chair",image:chairImg},{id:"clock",name:"Clock",image:clockImg},{id:"key",name:"Key",image:keyImg},{id:"umbrella",name:"Umbrella",image:umbrellaImg},
{id:"flower",name:"Flower",image:flowerImg},{id:"park",name:"Park",image:parkImg},{id:"plant",name:"Plant",image:plantImg},{id:"tree",name:"Tree",image:treeImg},
{id:"dress",name:"Dress",image:dressImg},{id:"glasses",name:"Glasses",image:glassesImg},{id:"hat",name:"Hat",image:hatImg},{id:"shoes",name:"Shoes",image:shoesImg},
{id:"book",name:"Book",image:bookImg},{id:"bottle",name:"Bottle",image:bottleImg},{id:"pen",name:"Pen",image:penImg},{id:"wallet",name:"Wallet",image:walletImg}
];
const CONFIG:Record<Difficulty,DifficultyConfig>={Easy:{objects:3,viewTime:8,rounds:3,choices:3},Medium:{objects:4,viewTime:6,rounds:4,choices:4},Hard:{objects:6,viewTime:5,rounds:5,choices:4}};
const T={
English:{brandSubtitle:"Memory & Cognitive Support",back:"Back to Activities",eyebrow:"MEMORY & ATTENTION",title:"What's missing?",description:"Look at the pictures carefully. One of them will disappear. Try to remember which picture is missing.",tip:"Memory tip",tipText:"Name each object quietly to yourself while you look at it.",correct:"Correct",accuracy:"Accuracy",time:"Time",round:"Round",difficulty:"Difficulty",pictures:"pictures",newGame:"New Game",ready:"Ready to remember?",start:"Start Activity",look:"LOOK & REMEMBER",remember:"Remember these pictures",missing:"ONE IS MISSING",which:"Which picture disappeared?",remain:"These pictures remain:",choose:"Choose the missing picture",correctLabel:"CORRECT",rememberLabel:"LET'S REMEMBER",found:"You found it",missingWas:"The missing picture was",results:"See Results",next:"Next Round",complete:"ACTIVITY COMPLETE",well:"Well done",completed:"You completed all",rounds:"rounds.",saved:"Activity saved to your progress.",recommendationSaved:"Recommendation saved.",adaptive:"ADAPTIVE RECOMMENDATION",nextLevel:"Next activity level",playNext:"Play next level",how:"How to play",step1:"Look carefully at every picture.",step2:"After a few seconds, one picture will disappear.",step3:"Choose the picture you remember seeing before.",listen:"Listen to instructions",calm:"Take your time. A wrong answer simply gives you another opportunity to remember.",strongHard:"You performed strongly. Hard level will continue for the next activity.",strongIncrease:"You performed strongly, so the next activity will be a little more challenging.",maintain:"This level suits your current performance, so the next activity will stay at the same level.",easyContinue:"Easy level will continue so you can practise comfortably.",easier:"The next activity will be made a little easier for comfortable practice."},
Assamese:{brandSubtitle:"স্মৃতি আৰু জ্ঞানীয় সহায়",back:"কাৰ্যকলাপলৈ উভতি যাওক",eyebrow:"স্মৃতি আৰু মনোযোগ",title:"কি নাই?",description:"ছবিসমূহ ভালদৰে চাওক। ইয়াৰে এখন ছবি নোহোৱা হ'ব। কোনখন ছবি নোহোৱা হৈছে মনত পেলাবলৈ চেষ্টা কৰক।",tip:"স্মৃতিৰ পৰামৰ্শ",tipText:"প্ৰতিটো বস্তু চোৱাৰ সময়ত তাৰ নামটো মনে মনে কওক।",correct:"শুদ্ধ",accuracy:"সঠিকতা",time:"সময়",round:"ৰাউণ্ড",difficulty:"কঠিনতাৰ স্তৰ",pictures:"খন ছবি",newGame:"নতুন খেল",ready:"মনত ৰাখিবলৈ সাজু নে?",start:"কাৰ্যকলাপ আৰম্ভ কৰক",look:"চাওক আৰু মনত ৰাখক",remember:"এই ছবিসমূহ মনত ৰাখক",missing:"এখন ছবি নাই",which:"কোনখন ছবি নোহোৱা হ'ল?",remain:"এই ছবিসমূহ এতিয়াও আছে:",choose:"নোহোৱা ছবিখন বাছনি কৰক",correctLabel:"শুদ্ধ",rememberLabel:"আকৌ মনত পেলাওঁ",found:"আপুনি বিচাৰি পালে",missingWas:"নোহোৱা ছবিখন আছিল",results:"ফলাফল চাওক",next:"পৰৱৰ্তী ৰাউণ্ড",complete:"কাৰ্যকলাপ সম্পূৰ্ণ",well:"খুব ভাল",completed:"আপুনি সকলো",rounds:"টা ৰাউণ্ড সম্পূৰ্ণ কৰিলে।",saved:"কাৰ্যকলাপটো আপোনাৰ অগ্ৰগতিত সংৰক্ষণ কৰা হৈছে।",recommendationSaved:"পৰামৰ্শ সংৰক্ষণ কৰা হৈছে।",adaptive:"অভিযোজিত পৰামৰ্শ",nextLevel:"পৰৱৰ্তী কাৰ্যকলাপৰ স্তৰ",playNext:"পৰৱৰ্তী স্তৰ খেলক",how:"কেনেকৈ খেলিব",step1:"প্ৰতিখন ছবি ভালদৰে চাওক।",step2:"কেইছেকেণ্ডমানৰ পিছত এখন ছবি নোহোৱা হ'ব।",step3:"আগতে দেখা বুলি মনত পৰা ছবিখন বাছনি কৰক।",listen:"নিৰ্দেশনা শুনক",calm:"লাহে লাহে কৰক। ভুল উত্তৰ হ'লেও পুনৰ মনত পেলাবলৈ সুযোগ পাব।",strongHard:"আপুনি ভাল প্ৰদৰ্শন কৰিছে। কঠিন স্তৰ অব্যাহত থাকিব।",strongIncrease:"আপুনি ভাল প্ৰদৰ্শন কৰিছে, সেয়ে পৰৱৰ্তী কাৰ্যকলাপ অলপ অধিক কঠিন হ'ব।",maintain:"বৰ্তমানৰ প্ৰদৰ্শনৰ বাবে একে স্তৰ অব্যাহত থাকিব।",easyContinue:"আৰামদায়ক অনুশীলনৰ বাবে সহজ স্তৰ অব্যাহত থাকিব।",easier:"আৰামদায়ক অনুশীলনৰ বাবে পৰৱৰ্তী কাৰ্যকলাপ অলপ সহজ হ'ব।"}
};
const AS:Record<string,string>={apple:"আপেল",banana:"কল",mango:"আম",strawberry:"ষ্ট্ৰবেৰী",chair:"চকী",clock:"ঘড়ী",key:"চাবি",umbrella:"ছাতি",flower:"ফুল",park:"উদ্যান",plant:"গছপুলি",tree:"গছ",dress:"পোছাক",glasses:"চশমা",hat:"টুপি",shoes:"জোতা",book:"কিতাপ",bottle:"বটল",pen:"কলম",wallet:"মানিবেগ"};
function shuffle<T>(a:T[]){const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]];}return x;}
function patientId(){try{const r=localStorage.getItem("user");return r?JSON.parse(r)?.patientId:undefined}catch{return undefined}}
function adaptive(d:Difficulty,a:number):Difficulty{if(a>=85)return d==="Easy"?"Medium":d==="Medium"?"Hard":"Hard";if(a>=50)return d;return d==="Hard"?"Medium":d==="Medium"?"Easy":"Easy";}
function reason(d:Difficulty,n:Difficulty,a:number){if(a>=85)return d==="Hard"?"Strong performance recorded. Hard difficulty is recommended to continue.":`Strong performance recorded. Difficulty is recommended to increase from ${d} to ${n}.`;if(a>=50)return`Current performance is suited to ${d}, so the same difficulty is recommended.`;if(d==="Easy")return"Easy difficulty is recommended to continue for comfortable practice.";return`A lower difficulty is recommended for comfortable practice, moving from ${d} to ${n}.`;}

function WhatsMissingGame(){
 const navigate=useNavigate(),saveStarted=useRef(false),previous=useRef<string[]>([]);
 const [language,setLanguage]=useState<AppLanguage>(getStoredLanguage()),lang=getLanguageOption(language),text=language==="Assamese"?T.Assamese:T.English;
 const [difficulty,setDifficulty]=useState<Difficulty>("Easy"),[phase,setPhase]=useState<GamePhase>("ready"),[round,setRound]=useState(1),[roundItems,setRoundItems]=useState<GameItem[]>([]),[remaining,setRemaining]=useState<GameItem[]>([]),[missing,setMissing]=useState<GameItem|null>(null),[choices,setChoices]=useState<GameItem[]>([]),[selected,setSelected]=useState<string|null>(null),[correct,setCorrect]=useState(0),[attempts,setAttempts]=useState(0),[time,setTime]=useState(0),[countdown,setCountdown]=useState(0),[lastCorrect,setLastCorrect]=useState<boolean|null>(null),[saved,setSaved]=useState(false),[recSaved,setRecSaved]=useState(false);
 const config=CONFIG[difficulty],accuracy=useMemo(()=>attempts?Math.round(correct/attempts*100):0,[correct,attempts]),nextDifficulty=useMemo(()=>adaptive(difficulty,accuracy),[difficulty,accuracy]);
 const message=accuracy>=85?(difficulty==="Hard"?text.strongHard:text.strongIncrease):accuracy>=50?text.maintain:difficulty==="Easy"?text.easyContinue:text.easier;
 const name=(i:GameItem)=>language==="Assamese"?(AS[i.id]||i.name):i.name, level=(d:Difficulty)=>language==="Assamese"?(d==="Easy"?"সহজ":d==="Medium"?"মধ্যম":"কঠিন"):d;
 function prepare(d:Difficulty=difficulty){const c=CONFIG[d];let available=GAME_ITEMS.filter(i=>!previous.current.includes(i.id));if(available.length<c.objects)available=GAME_ITEMS;const items=shuffle(available).slice(0,c.objects);previous.current=items.map(i=>i.id);setRoundItems(items);setRemaining([]);setMissing(null);setChoices([]);setSelected(null);setLastCorrect(null);setCountdown(c.viewTime);setPhase("memorize");}
 function resetSave(){setSaved(false);setRecSaved(false);saveStarted.current=false;}
 function start(d:Difficulty=difficulty){setDifficulty(d);setRound(1);setCorrect(0);setAttempts(0);setTime(0);resetSave();previous.current=[];prepare(d);}
 function reset(){setPhase("ready");setRound(1);setRoundItems([]);setRemaining([]);setMissing(null);setChoices([]);setSelected(null);setCorrect(0);setAttempts(0);setTime(0);setCountdown(0);setLastCorrect(null);resetSave();previous.current=[];}
 useEffect(()=>{if(phase==="ready"||phase==="complete")return;const id=window.setInterval(()=>setTime(v=>v+1),1000);return()=>window.clearInterval(id);},[phase]);
 useEffect(()=>{if(phase!=="memorize")return;if(countdown<=0){const m=roundItems[Math.floor(Math.random()*roundItems.length)];if(!m)return;setMissing(m);setRemaining(roundItems.filter(i=>i.id!==m.id));const ds=shuffle(GAME_ITEMS.filter(i=>!roundItems.some(r=>r.id===i.id))).slice(0,config.choices-1);setChoices(shuffle([m,...ds]));setPhase("question");return;}const id=window.setTimeout(()=>setCountdown(v=>v-1),1000);return()=>window.clearTimeout(id);},[phase,countdown,roundItems,config.choices]);
 function answer(i:GameItem){if(phase!=="question"||!missing||selected)return;const ok=i.id===missing.id;setSelected(i.id);setAttempts(v=>v+1);setLastCorrect(ok);if(ok)setCorrect(v=>v+1);setPhase("feedback");}
 function next(){if(round>=config.rounds){setPhase("complete");return;}setRound(v=>v+1);prepare();}
 useEffect(()=>{if(phase!=="complete"||saveStarted.current)return;const id=patientId();if(!id)return;saveStarted.current=true;(async()=>{try{await saveGameSession({patientId:id,gameName:"What's Missing",score:correct*10,totalQuestions:attempts,accuracy,difficulty});setSaved(true);await saveRecommendation({patientId:id,gameName:"What's Missing",currentDifficulty:difficulty,recommendedDifficulty:nextDifficulty,reason:reason(difficulty,nextDifficulty,accuracy),accuracy});setRecSaved(true);}catch(e){console.error("Failed to save What's Missing result:",e);saveStarted.current=false;}})();},[phase,correct,attempts,accuracy,difficulty,nextDifficulty]);
 function speak(){if(!("speechSynthesis"in window))return;window.speechSynthesis.cancel();const s=new SpeechSynthesisUtterance(phase==="complete"?`${text.complete} ${accuracy}%. ${text.nextLevel}: ${level(nextDifficulty)}.`:text.description);s.lang=lang.speechCode;s.rate=.88;window.speechSynthesis.speak(s);}
 const fmt=(s:number)=>`${Math.floor(s/60)}:${(s%60).toString().padStart(2,"0")}`;
 function changeLanguage(v:AppLanguage){if("speechSynthesis"in window)window.speechSynthesis.cancel();setLanguage(v);saveLanguage(v);}
 return <main className="wm-page"><header className="wm-header"><button className="wm-brand" type="button" onClick={()=>navigate("/home")}><span className="wm-logo">S</span><span><strong>SMRITI</strong><small>{text.brandSubtitle}</small></span></button><div style={{marginLeft:"auto",display:"flex",alignItems:"center",gap:7}}><Globe2 size={17}/><select value={language} onChange={e=>changeLanguage(e.target.value as AppLanguage)}>{SUPPORTED_LANGUAGES.map(o=><option key={o.code} value={o.name}>{o.nativeName} — {o.name}</option>)}</select></div><button className="wm-back" type="button" onClick={()=>navigate("/games")}><ArrowLeft size={21}/>{text.back}</button></header>
 <div className="wm-content"><section className="wm-intro"><span className="wm-eyebrow">{text.eyebrow}</span><h1>{text.title}</h1><p>{text.description}</p><div className="wm-tip"><Lightbulb size={23}/><div><strong>{text.tip}</strong><span>{text.tipText}</span></div></div></section>
 <section className="wm-stats"><div className="wm-stat"><span className="wm-stat-icon"><Award size={24}/></span><div><span>{text.correct}</span><strong>{correct}/{config.rounds}</strong></div></div><div className="wm-stat"><span className="wm-stat-icon"><BarChart3 size={24}/></span><div><span>{text.accuracy}</span><strong>{accuracy}%</strong></div></div><div className="wm-stat"><span className="wm-stat-icon"><Clock3 size={24}/></span><div><span>{text.time}</span><strong>{fmt(time)}</strong></div></div><div className="wm-stat"><span className="wm-stat-icon"><Eye size={24}/></span><div><span>{text.round}</span><strong>{Math.min(round,config.rounds)}/{config.rounds}</strong></div></div></section>
 <section className="wm-controls"><div><span className="wm-control-label">{text.difficulty}</span><div className="wm-difficulties">{(["Easy","Medium","Hard"]as Difficulty[]).map(d=><button type="button" key={d} className={difficulty===d?"wm-difficulty active":"wm-difficulty"} onClick={()=>{setDifficulty(d);reset();}}><strong>{level(d)}</strong><span>{CONFIG[d].objects} {text.pictures}</span></button>)}</div></div><button type="button" className="wm-new-game" onClick={reset}><Shuffle size={20}/>{text.newGame}</button></section>
 <section className="wm-game-layout"><div className="wm-game-area">
 {phase==="ready"&&<div className="wm-ready"><div className="wm-ready-icon"><Eye size={34}/></div><h2>{text.ready}</h2><p>{CONFIG[difficulty].viewTime} seconds · {CONFIG[difficulty].objects} {text.pictures}</p><button type="button" className="wm-primary" onClick={()=>start()}><Play size={21}/>{text.start}</button></div>}
 {phase==="memorize"&&<><div className="wm-phase-heading"><div><span>{text.look}</span><h2>{text.remember}</h2></div><div className="wm-countdown"><Clock3 size={21}/>{countdown}s</div></div><div className="wm-picture-grid">{roundItems.map(i=><div className="wm-picture-card" key={i.id}><img src={i.image} alt={name(i)}/><strong>{name(i)}</strong></div>)}</div></>}
 {phase==="question"&&<><div className="wm-phase-heading"><div><span>{text.missing}</span><h2>{text.which}</h2></div></div><p className="wm-question-help">{text.remain}</p><div className="wm-remaining-grid">{remaining.map(i=><div className="wm-small-picture" key={i.id}><img src={i.image} alt={name(i)}/><strong>{name(i)}</strong></div>)}</div><div className="wm-answer-section"><h3>{text.choose}</h3><div className="wm-answer-grid">{choices.map(i=><button type="button" key={i.id} className="wm-answer-card" onClick={()=>answer(i)}><img src={i.image} alt={name(i)}/><strong>{name(i)}</strong></button>)}</div></div></>}
 {phase==="feedback"&&missing&&<div className="wm-feedback"><div className={lastCorrect?"wm-feedback-icon correct":"wm-feedback-icon"}>{lastCorrect?<Check size={31}/>:<Eye size={31}/>}</div><span className="wm-feedback-label">{lastCorrect?text.correctLabel:text.rememberLabel}</span><h2>{lastCorrect?text.found:`${text.missingWas} ${name(missing)}`}</h2><div className="wm-reveal-card"><img src={missing.image} alt={name(missing)}/><strong>{name(missing)}</strong></div><button type="button" className="wm-primary" onClick={next}>{round>=config.rounds?text.results:text.next}</button></div>}
 {phase==="complete"&&<div className="wm-complete"><div className="wm-complete-check"><Check size={32}/></div><span>{text.complete}</span><h2>{text.well}</h2><p>{text.completed} {config.rounds} {text.rounds}</p><div className="wm-results"><div><span>{text.correct}</span><strong>{correct}/{config.rounds}</strong></div><div><span>{text.accuracy}</span><strong>{accuracy}%</strong></div><div><span>{text.time}</span><strong>{fmt(time)}</strong></div><div><span>{text.difficulty}</span><strong>{level(difficulty)}</strong></div></div>{saved&&<p className="wm-saved"><Check size={18}/>{text.saved}</p>}{recSaved&&<p className="wm-saved"><Check size={18}/>{text.recommendationSaved}</p>}<div style={{marginTop:22,marginBottom:22,padding:"18px 20px",borderRadius:14,background:"#f4f7f2",textAlign:"left"}}><span style={{display:"block",fontSize:12,fontWeight:800,color:"#8c6a17"}}>{text.adaptive}</span><strong style={{display:"block",margin:"7px 0",fontSize:18,color:"#123d31"}}>{text.nextLevel}: {level(nextDifficulty)}</strong><p style={{margin:0}}>{message}</p></div><div className="wm-complete-actions"><button type="button" className="wm-secondary" onClick={()=>navigate("/games")}><ArrowLeft size={19}/>{text.back}</button><button type="button" className="wm-primary" onClick={()=>start(nextDifficulty)}><Shuffle size={19}/>{text.playNext}</button></div></div>}
 </div><aside className="wm-instructions"><h2>{text.how}</h2><div className="wm-step"><span>1</span><p>{text.step1}</p></div><div className="wm-step"><span>2</span><p>{text.step2}</p></div><div className="wm-step"><span>3</span><p>{text.step3}</p></div><button type="button" className="wm-listen" onClick={speak}><Volume2 size={20}/>{text.listen}</button><p className="wm-calm">{text.calm}</p></aside></section></div></main>;
}
export default WhatsMissingGame;
